services:
  postgres:
    image: 'postgres:15.0'
    environment:
      - 'POSTGRES_DB=weightminder'
      - 'POSTGRES_PASSWORD=spomprt'
      - 'POSTGRES_USER=spomprt'
    volumes:
      - ./postgres/weightminder:/var/lib/postgresql/data
    ports:
      - '5432:5432'
