server:
  port: ${PORT}

telegram:
  bot:
    token: 6870085716:AAH0SbM-KZSR4yb-rozhb4-2rlsI9Kb451s

spring:
  datasource:
    url: jdbc:postgresql://${PG_DOMAIN_NAME}:${PG_PORT}/${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          shortener-client:
            default-request-headers:
              x-rapidapi-key: a9388f8939msh947f0fe994d4633p14e2e6jsnb35bb2c22af2
  jpa:
    open-in-view: false

cache:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    user: ${REDIS_USER}
    password: ${REDIS_PASSWORD}

external:
  shortener:
    url: https://blinkify.up.railway.app/blinkify/api/v1
  quickchart:
    url: https://quickchart.io/chart?c=

javamelody:
  enabled: true

