telegram:
  bot:
    token: 6870085716:AAHY-TrZn4fB5fHDD_seTF39dpk9pfZQ8zE

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          shortener-client:
            default-request-headers:
              x-rapidapi-key: a9388f8939msh947f0fe994d4633p14e2e6jsnb35bb2c22af2

cache:
  redis:
    host: localhost
    port: 6379

external:
  shortener:
    url: https://spomprt.ru/blinkify/api/v1
  quickchart:
    url: https://quickchart.io/chart?c=

javamelody:
  enabled: true

