server:
  port: ${PORT}

telegram:
  bot:
    token: 6870085716:AAH0SbM-KZSR4yb-rozhb4-2rlsI9Kb451s

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          shortener-client:
            default-request-headers:
              x-rapidapi-key: a9388f8939msh947f0fe994d4633p14e2e6jsnb35bb2c22af2

cache:
  redis:
    host: ${CACHE_REDIS_HOST}
    port: ${CACHE_REDIS_PORT}
    user: ${CACHE_REDIS_USER}
    password: ${CACHE_REDIS_PASSWORD}

external:
  shortener:
    url: https://blinkify.up.railway.app/blinkify/api/v1
  quickchart:
    url: https://quickchart.io/chart?c=

javamelody:
  enabled: true

