name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Create JAR
        run: mvn clean package -DskipTests=true

      - name: Generate app version
        run: echo "WEIGHT_MINDER_APP_VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: actions/checkout@v3
        run: docker build -t spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }} .

      - name: Push to Docker Hub
        run: docker push docker.io/spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}
