name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn clean package -DskipTests=true
    - run: mkdir app && cp target/*.jar app/
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
    - run: echo "WEIGHT_MINDER_APP_VERSION=$(date +%s)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}
      
    - run: docker push docker.io/spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}
