name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - run: mvn clean package -DskipTests=true

      - run: echo "WEIGHT_MINDER_APP_VERSION=$(date +%s)" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }} .

      - run: docker push docker.io/spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}
