name: Publish Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Generate app version
        run: echo "WEIGHT_MINDER_APP_VERSION=$(date +%s)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps -a | awk -v i="^spomprt1/weightminder.*" '{if($2~i){print$1}}')
            docker rm $(docker ps -a | awk -v i="^spomprt1/weightminder.*" '{if($2~i){print$1}}')
            docker run -d -t -i -e SPRING_DATASOURCE_URL='jdbc:postgresql://172.17.0.2:5432/weightminder' -e SPRING_DATASOURCE_USERNAME='spomprt' -e SPRING_DATASOURCE_PASSWORD='spomprt' -p 8080:8080 --name weightminder docker.io/spomprt1/weightminder:${{ env.WEIGHT_MINDER_APP_VERSION }}